# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('userid', models.BigIntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'currency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='$', max_length=20)),
                ('currency_name', models.CharField(default='candy', max_length=50)),
                ('currency_plrname', models.CharField(default='candies', max_length=50)),
                ('currency_sign', models.CharField(default='🍬', max_length=50)),
                ('owner', models.CharField(default='None', max_length=100)),
            ],
            options={
                'db_table': 'settings',
                'managed': True,
            },
        ),
    ]
